<a href="https://colab.research.google.com/github/arturdiel/unijui-prog-ciencia-de-dados/blob/main/07_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Importando a biblioteca
import numpy as np

# Exibe os números sem notação científica e com 2 casas decimais
np.set_printoptions(suppress=True, precision=2)

In [3]:
# Dados da semana: cada linha é um dia
dados = np.array([
    [120, 15000, 100, 125.00, 4],
    [135, 16200, 108, 120.00, 5],
    [98, 11700, 82, 119.39, 3],
    [150, 21000, 125, 140.00, 7],
    [175, 24500, 140, 140.00, 9],
    [160, 22400, 132, 140.00, 6],
    [110, 13200, 95, 120.00, 2]
])

dias = np.array([
    "Segunda",
    "Terça",
    "Quarta",
    "Quinta",
    "Sexta",
    "Sábado",
    "Domingo"
])

# Nome de cada coluna de dados, na mesma ordem
indicadores = np.array([
    "Pedidos",
    "Faturamento",
    "Clientes",
    "Ticket_Medio",
    "Reclamações"
])

In [4]:
# 1.1 - Estrutura do array
print("Quantidade de linhas:", dados.shape[0])
print("Quantidade de colunas:", dados.shape[1])
print("Quantidade total de valores:", dados.size)
print("Número de dimensões:", dados.ndim)
print("Tipo dos dados:", dados.dtype)

Quantidade de linhas: 7
Quantidade de colunas: 5
Quantidade total de valores: 35
Número de dimensões: 2
Tipo dos dados: float64


In [5]:
# 2.1 - Dados da sexta-feira (linha de índice 4)
print("Sexta-feira:", dados[4])

Sexta-feira: [  175. 24500.   140.   140.     9.]


In [6]:
# 2.2 - Faturamento de todos os dias (coluna de índice 1)
faturamento = dados[:, 1]
print(faturamento)

[15000. 16200. 11700. 21000. 24500. 22400. 13200.]


In [7]:
# 2.3 - Reclamações de todos os dias (coluna de índice 4)
reclamacoes = dados[:, 4]
print(reclamacoes)

[4. 5. 3. 7. 9. 6. 2.]


In [8]:
# 2.4 - De quinta-feira (índice 3) até o fim do array (domingo)
print(dias[3:])
print(dados[3:])

['Quinta' 'Sexta' 'Sábado' 'Domingo']
[[  150. 21000.   125.   140.     7.]
 [  175. 24500.   140.   140.     9.]
 [  160. 22400.   132.   140.     6.]
 [  110. 13200.    95.   120.     2.]]


In [9]:
# 2.5 - Colunas de pedidos, faturamento e clientes (índices 0, 1 e 2; o 3 não entra)
print(dados[:, 0:3])

[[  120. 15000.   100.]
 [  135. 16200.   108.]
 [   98. 11700.    82.]
 [  150. 21000.   125.]
 [  175. 24500.   140.]
 [  160. 22400.   132.]
 [  110. 13200.    95.]]


In [10]:
# Separando as demais colunas usadas nas próximas partes
pedidos = dados[:, 0]
clientes = dados[:, 2]

In [11]:
# 3.1 - Total de pedidos da semana
print(f"Total de pedidos: {np.sum(pedidos):.0f}")

# 3.2 - Faturamento total
print(f"Faturamento total: R$ {np.sum(faturamento):.2f}")

# 3.3 - Total de clientes
print(f"Total de clientes: {np.sum(clientes):.0f}")

# 3.4 - Média diária de pedidos
print(f"Média diária de pedidos: {np.mean(pedidos):.2f}")

# 3.5 - Média diária de faturamento
print(f"Média diária de faturamento: R$ {np.mean(faturamento):.2f}")

# 3.6 - Média de reclamações por dia
print(f"Média de reclamações por dia: {np.mean(reclamacoes):.2f}")

Total de pedidos: 948
Faturamento total: R$ 124000.00
Total de clientes: 782
Média diária de pedidos: 135.43
Média diária de faturamento: R$ 17714.29
Média de reclamações por dia: 5.14


In [12]:
# 4.1 - Dias com maior e menor número de pedidos
# argmax e argmin devolvem o índice (posição), que é usado para buscar o nome em dias
indice_mais_pedidos = np.argmax(pedidos)
indice_menos_pedidos = np.argmin(pedidos)

print(f"Maior número de pedidos: {dias[indice_mais_pedidos]} ({pedidos[indice_mais_pedidos]:.0f} pedidos)")
print(f"Menor número de pedidos: {dias[indice_menos_pedidos]} ({pedidos[indice_menos_pedidos]:.0f} pedidos)")

Maior número de pedidos: Sexta (175 pedidos)
Menor número de pedidos: Quarta (98 pedidos)


In [13]:
# 4.2 - Dias com maior e menor faturamento
indice_maior_faturamento = np.argmax(faturamento)
indice_menor_faturamento = np.argmin(faturamento)

print(f"Maior faturamento: {dias[indice_maior_faturamento]} (R$ {faturamento[indice_maior_faturamento]:.2f})")
print(f"Menor faturamento: {dias[indice_menor_faturamento]} (R$ {faturamento[indice_menor_faturamento]:.2f})")

Maior faturamento: Sexta (R$ 24500.00)
Menor faturamento: Quarta (R$ 11700.00)


In [14]:
# 4.3 - Amplitude do faturamento (maior - menor)
amplitude = np.max(faturamento) - np.min(faturamento)
print(f"Amplitude do faturamento: R$ {amplitude:.2f}")

Amplitude do faturamento: R$ 12800.00


In [15]:
# 5.1 - Dias com faturamento superior a R$ 20.000
faturamento_acima_20000 = faturamento > 20000
print(dias[faturamento_acima_20000])

['Quinta' 'Sexta' 'Sábado']


In [16]:
# 5.2 - Dias com mais de 150 pedidos
mais_de_150_pedidos = pedidos > 150
print(dias[mais_de_150_pedidos])

['Sexta' 'Sábado']


In [17]:
# 5.3 - Dias com mais de 5 reclamações
mais_de_5_reclamacoes = reclamacoes > 5
print(dias[mais_de_5_reclamacoes])

['Quinta' 'Sexta' 'Sábado']


In [18]:
# 5.4 - Faturamento dos dias com mais de 150 pedidos
# (a máscara dos pedidos é aplicada no array do faturamento)
print(faturamento[mais_de_150_pedidos])

[24500. 22400.]


In [19]:
# 5.5 - Dias com faturamento abaixo da média semanal
media_faturamento = np.mean(faturamento)
abaixo_da_media = faturamento < media_faturamento

print(f"Média semanal: R$ {media_faturamento:.2f}")
print("Dias abaixo da média:", dias[abaixo_da_media])
# np.sum conta os True, pois True vale 1 e False vale 0
print("Quantidade de dias:", np.sum(abaixo_da_media))

Média semanal: R$ 17714.29
Dias abaixo da média: ['Segunda' 'Terça' 'Quarta' 'Domingo']
Quantidade de dias: 4


In [20]:
# 6.1 - Classificação de cada dia
# np.where(condição, valor se True, valor se False)
classificacao = np.where(
    faturamento >= 20000,
    "Alto desempenho",
    "Desempenho normal"
)

print(classificacao)

# junta dias e classificacao em uma matriz; o .T (transposta) deixa cada dia ao lado da sua classificação
print(np.array([dias, classificacao]).T)

['Desempenho normal' 'Desempenho normal' 'Desempenho normal'
 'Alto desempenho' 'Alto desempenho' 'Alto desempenho' 'Desempenho normal']
[['Segunda' 'Desempenho normal']
 ['Terça' 'Desempenho normal']
 ['Quarta' 'Desempenho normal']
 ['Quinta' 'Alto desempenho']
 ['Sexta' 'Alto desempenho']
 ['Sábado' 'Alto desempenho']
 ['Domingo' 'Desempenho normal']]


In [21]:
# 6.2 - Quantidade de dias de alto desempenho
alto_desempenho = classificacao == "Alto desempenho"
print("Dias de alto desempenho:", np.sum(alto_desempenho))

Dias de alto desempenho: 3


In [22]:
# Medidas estatísticas do faturamento
media = np.mean(faturamento)
mediana = np.median(faturamento)
desvio_padrao = np.std(faturamento)
minimo = np.min(faturamento)
maximo = np.max(faturamento)

print(f"Média: R$ {media:.2f}")
print(f"Mediana: R$ {mediana:.2f}")
print(f"Desvio padrão: R$ {desvio_padrao:.2f}")
print(f"Mínimo: R$ {minimo:.2f}")
print(f"Máximo: R$ {maximo:.2f}")

# quanto o desvio padrão representa da média
print(f"Desvio padrão em relação à média: {desvio_padrao / media * 100:.2f}%")

Média: R$ 17714.29
Mediana: R$ 16200.00
Desvio padrão: R$ 4551.43
Mínimo: R$ 11700.00
Máximo: R$ 24500.00
Desvio padrão em relação à média: 25.69%


In [23]:
# Ordem dos indicadores nos resultados
print(indicadores)

# 8.1 - Média de cada indicador na semana
medias = np.mean(dados, axis=0)
print("Média:", medias)

# 8.2 - Maior valor de cada indicador
maiores = np.max(dados, axis=0)
print("Maior:", maiores)

# 8.3 - Menor valor de cada indicador
menores = np.min(dados, axis=0)
print("Menor:", menores)

['Pedidos' 'Faturamento' 'Clientes' 'Ticket_Medio' 'Reclamações']
Média: [  135.43 17714.29   111.71   129.2      5.14]
Maior: [  175. 24500.   140.   140.     9.]
Menor: [   98.   11700.      82.     119.39     2.  ]


In [24]:
# 8.4 - Variação relativa: amplitude (maior - menor) dividida pela média
# a conta é feita para os 5 indicadores de uma vez
variacao_relativa = (maiores - menores) / medias
print(indicadores)
print("Variação relativa:", variacao_relativa)

indice_maior_variacao = np.argmax(variacao_relativa)
print("Maior variação relativa:", indicadores[indice_maior_variacao])

['Pedidos' 'Faturamento' 'Clientes' 'Ticket_Medio' 'Reclamações']
Variação relativa: [0.57 0.72 0.52 0.16 1.36]
Maior variação relativa: Reclamações


In [25]:
# 9.1 - Melhor dia da semana pelo faturamento
indice_melhor_dia = np.argmax(faturamento)
print(f"Melhor dia: {dias[indice_melhor_dia]} (R$ {faturamento[indice_melhor_dia]:.2f})")

Melhor dia: Sexta (R$ 24500.00)


In [26]:
# 9.2 - O melhor dia também teve a maior quantidade de pedidos?
indice_mais_pedidos = np.argmax(pedidos)
print("Dia com mais pedidos:", dias[indice_mais_pedidos])

if indice_melhor_dia == indice_mais_pedidos:
    print("Sim, o dia de maior faturamento também teve mais pedidos.")
else:
    print("Não, o dia de maior faturamento não foi o de mais pedidos.")

Dia com mais pedidos: Sexta
Sim, o dia de maior faturamento também teve mais pedidos.


In [27]:
# 9.3 - O dia de maior faturamento também teve mais reclamações?
indice_mais_reclamacoes = np.argmax(reclamacoes)
print("Dia com mais reclamações:", dias[indice_mais_reclamacoes])

if indice_melhor_dia == indice_mais_reclamacoes:
    print("Sim, o dia de maior faturamento também teve mais reclamações.")
else:
    print("Não, o dia de maior faturamento não foi o de mais reclamações.")

Dia com mais reclamações: Sexta
Sim, o dia de maior faturamento também teve mais reclamações.


In [28]:
# 9.4 - Dias com mais de 150 pedidos E faturamento acima de R$ 20.000
# o & exige que as duas condições sejam True no mesmo dia
pedidos_e_faturamento_altos = (pedidos > 150) & (faturamento > 20000)

print("Dias:", dias[pedidos_e_faturamento_altos])
print("Quantidade:", np.sum(pedidos_e_faturamento_altos))

Dias: ['Sexta' 'Sábado']
Quantidade: 2


In [29]:
# Separando as colunas
pedidos = dados[:, 0]
faturamento = dados[:, 1]
reclamacoes = dados[:, 4]

# Índices do melhor dia, do pior dia e do dia com mais reclamações
indice_melhor_dia = np.argmax(faturamento)
indice_pior_dia = np.argmin(faturamento)
indice_mais_reclamacoes = np.argmax(reclamacoes)

# Dias com faturamento de R$ 20.000 ou mais
dias_alto_desempenho = dias[faturamento >= 20000]

# Exibindo o resumo
print("RESUMO DA SEMANA")
print(f"Total de pedidos: {np.sum(pedidos):.0f}")
print(f"Faturamento total: R$ {np.sum(faturamento):.2f}")
print(f"Média diária de pedidos: {np.mean(pedidos):.2f}")
print(f"Média diária de faturamento: R$ {np.mean(faturamento):.2f}")
print(f"Melhor dia: {dias[indice_melhor_dia]} (R$ {faturamento[indice_melhor_dia]:.2f})")
print(f"Pior dia: {dias[indice_pior_dia]} (R$ {faturamento[indice_pior_dia]:.2f})")
print(f"Maior número de reclamações: {reclamacoes[indice_mais_reclamacoes]:.0f} ({dias[indice_mais_reclamacoes]})")
print(f"Dias de alto desempenho: {dias_alto_desempenho.size} {dias_alto_desempenho}")

RESUMO DA SEMANA
Total de pedidos: 948
Faturamento total: R$ 124000.00
Média diária de pedidos: 135.43
Média diária de faturamento: R$ 17714.29
Melhor dia: Sexta (R$ 24500.00)
Pior dia: Quarta (R$ 11700.00)
Maior número de reclamações: 9 (Sexta)
Dias de alto desempenho: 3 ['Quinta' 'Sexta' 'Sábado']


In [30]:
# Reclamações a cada 100 pedidos (divide um array pelo outro, dia a dia)
reclamacoes_por_100_pedidos = reclamacoes / pedidos * 100
print(dias)
print(reclamacoes_por_100_pedidos)

['Segunda' 'Terça' 'Quarta' 'Quinta' 'Sexta' 'Sábado' 'Domingo']
[3.33 3.7  3.06 4.67 5.14 3.75 1.82]
